[project]
authors = ["Jonathan <jonsouyang@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "CalHacks-Project"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
manim = ">=0.18.1,<0.19"
